// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    [Migration("20230227015526_OverRide")]
    partial class OverRide
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app.Models.EmployeesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sector");

                    b.HasKey("Id");

                    b.ToTable("tb_employess", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Levi Mário Levi Monteiro",
                            Role = "CEO",
                            Sector = "Administrativo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Raquel Andreia Emilly Fogaça",
                            Role = "CTO",
                            Sector = "Administrativo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sônia Carolina Marcela da Silva",
                            Role = "Contabilidade",
                            Sector = "Financeiro"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Luiz Hugo Renan Dias",
                            Role = "Gestor de pessoas",
                            Sector = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antônia Bianca Lara Almeida",
                            Role = "DevOps",
                            Sector = "Operacional"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hugo Cauê Carlos Eduardo Martins",
                            Role = "Dev FrontEnd",
                            Sector = "Operacional"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cauê Matheus Nicolas Santos",
                            Role = "Dev BacktEnd",
                            Sector = "Operacional"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elias Luís Moreira",
                            Role = "PO",
                            Sector = "Comercial"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Eliane Melissa Barros",
                            Role = "Marketing",
                            Sector = "Comercial"
                        },
                        new
                        {
                            Id = 10,
                            Name = "José Hugo Araújo",
                            Role = "Atendimento",
                            Sector = "Comercial"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
